In [2]:
import numpy as np

In [4]:
data = np.load("/home/zimengchai/Documents/IsaacLab/source/isaaclab_assets/data/stepping_dataset_10.29.npz")
list(data.keys())

['q',
 'qd',
 'T_blf',
 'T_brf',
 'T_stsw',
 'p_wcom',
 'T_wbase',
 'v_b',
 'cmd_footstep',
 'cmd_stance',
 'cmd_countdown',
 'traj',
 'traj_dt']

In [6]:
data["q"].shape

(59449, 36)

In [ ]:
np.set_printoptions(suppress=True, precision=3)
print(data["T_blf"][0:58, :])
print()
print(data["T_brf"][0:57, :])
print()
print(data["cmd_footstep"][0:100, :])
print()
print(data["cmd_stance"][0:57, :])
print()
print(data["cmd_countdown"][0:57, :])

[[ 0.041  0.106 -0.636  0.   ]
 [ 0.041  0.106 -0.636  0.   ]
 [ 0.041  0.106 -0.636  0.   ]
 [ 0.041  0.106 -0.636  0.   ]
 [ 0.041  0.106 -0.636  0.   ]
 [ 0.041  0.106 -0.636  0.   ]
 [ 0.041  0.106 -0.636  0.   ]
 [ 0.041  0.106 -0.636  0.   ]
 [ 0.041  0.106 -0.636  0.   ]
 [ 0.041  0.106 -0.636  0.   ]
 [ 0.041  0.106 -0.636  0.   ]
 [ 0.041  0.106 -0.636  0.   ]
 [ 0.041  0.106 -0.636  0.   ]
 [ 0.041  0.106 -0.636  0.   ]
 [ 0.041  0.106 -0.636  0.   ]
 [ 0.041  0.106 -0.636  0.   ]
 [ 0.041  0.106 -0.636  0.   ]
 [ 0.041  0.106 -0.636  0.   ]
 [ 0.041  0.106 -0.636  0.   ]
 [ 0.041  0.106 -0.636  0.   ]
 [ 0.038  0.102 -0.636 -0.001]
 [ 0.041  0.096 -0.637  0.005]
 [ 0.043  0.096 -0.637  0.001]
 [ 0.045  0.096 -0.637 -0.001]
 [ 0.048  0.096 -0.638 -0.001]
 [ 0.05   0.095 -0.638 -0.001]
 [ 0.053  0.095 -0.638 -0.001]
 [ 0.055  0.095 -0.638 -0.001]
 [ 0.059  0.095 -0.638 -0.001]
 [ 0.062  0.095 -0.638 -0.001]
 [ 0.066  0.095 -0.639 -0.001]
 [ 0.069  0.096 -0.639 -0.001]
 [ 0.074